apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: physrisk
  namespace: openshift-gitops
spec:
  project: physrisk
  source:
    path: physrisk/kustomize/overlays/osc-cl2
    repoURL: https://github.com/redmikhail/ops-argocd.git
    targetRevision: argocd-migration
  destination:
    name: in-cluster
    namespace: physrisk
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
