apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-osc-cl1
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: osc-infra
  source:
    path: argocd/overlays/osc-cl1/applications/envs/osc/osc-cl1
    repoURL: https://github.com/redmikhail/ops-argocd.git
    targetRevision: argocd-migration
  # syncPolicy:
  #   syncOptions:
  #   - Validate=false
  #   - ApplyOutOfSyncOnly=true
