kind: Secret
apiVersion: v1
metadata:
  name: physrisk-s3-keys
data:
  HAZARD_INDICATORS_S3_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXX
  HAZARD_INDICATORS_S3_BUCKET: XXXXXXXXXXXXXXXXXXXXXXXX
  HAZARD_INDICATORS_S3_RO_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXX
  HAZARD_INDICATORS_S3_RO_SECRET_KEY: XXXXXXXXXXXXXXXXXXXXXXXX
  HAZARD_INDICATORS_S3_SECRET_KEY: XXXXXXXXXXXXXXXXXXXXXXXX
  OSC_S3_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXX
  OSC_S3_SECRET_KEY: XXXXXXXXXXXXXXXXXXXXXXXX
type: Opaque