---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudbeaver
spec:
  destination:
    name: in-cluster
    namespace: odh-trino
  project: os-climate
  source:
    path: cloudbeaver/overlays/osc/osc-cl1
    repoURL: https://github.com/redmikhail/ops-argocd.git
    targetRevision: argocd-migration
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
