---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-operator
spec:
  destination:
    name: in-cluster
    namespace: kubeflow
  project: os-climate
  source:
    path: training-operator/overlays/osc/osc-cl1
    repoURL: https://github.com/redmikhail/ops-argocd.git
    targetRevision: main
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
