apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: physrisk
configMapGenerator:
  - files:
      - configmaps/files/BaseUris.js
    name: base-uris
resources:
  - ../../base
  # - externalsecret.yaml

