---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-annotations-exporter
spec:
  destination:
    name: in-cluster
    namespace: opf-monitoring
  project: os-climate
  source:
    path: k8s-annotations-exporter/overlays/osc/osc-cl2
    repoURL: https://github.com/redmikhail/ops-argocd.git
    targetRevision: argocd-migration
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
