---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfp-tekton
spec:
  destination:
    name: in-cluster
    namespace: kubeflow
  project: os-climate
  source:
    path: kfp-tekton/overlays/osc/osc-cl2
    repoURL: https://github.com/redmikhail/ops-argocd.git
    targetRevision: argocd-migration
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
